server:
  port: 8085
  servlet:
    context-path: /mongodb
debug: true
logging:
  file:
    name: mongodb.log
    path: D:\\log
  level:
    root: warn
    org:
      springframework:
        data: 
          mongodb: DEBUG
        web: warn
      hibernate: warn
    com:
      xh: debug
spring:
  datasource:
    url: jdbc:mysql://47.98.142.170:3306/dream?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: accp
  data:
    mongodb:
      host: 47.98.142.170
      port: 28017
      database: dream
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xh.mongodb.entity